project:
  type: website
  output-dir: docs

website:
  title: "Pairs Trading"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd

    right:
      - icon: github
        href: https://github.com/buishuohua/PT_Unsupervised
        aria-label: GitHub

format:
  html:
    toc: true
    toc-location: right
    css: styles.css